# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: project
  name: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: the-project-image-pvc
      containers:
        - name: the-project
          image: buddy00/the-project:0.5.0
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: project-config
