# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # namespace: project
  name: the-project-ingress
spec:
  rules:
    - http:
        paths:
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: todo-backend-svc
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-project-svc
                port:
                  number: 1235
