apiVersion: v1
kind: Service
metadata:
  # namespace: project
  name: the-project-svc
spec:
  type: ClusterIP
  selector:
    app: the-project
  ports:
    - name: http
      protocol: TCP
      port: 1235
      targetPort: 3000
